# This Makefile was designed to run on Windows, so there may be some teething issues if you 
# try running it on Mac or Linux, but maybe not.
# Use this to compile/upload/monitor your Apex code.
# NOTE: You will need to install and setup arduino-cli for this to work

PORT = "${ARDUINO_PORT}" # Make sure to set this via `export ARDUINO_PORT=VALUE` for mac and linux or `$env:ARDUINO_PORT="VALUE"` for windows


bin/apex.ino.uf2:
    @echo "compiling"
	@echo "HI"